# fly.toml app configuration file generated for rogue-currency-t95i4a on 2025-09-27T23:39:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rogue-currency-t95i4a'
primary_region = "dfw"

[build]
dockerfile = "Dockerfile"

[processes]
app = "java -jar /app/app.jar"

[env]
JAVA_OPTS = "-XX:MaxRAMPercentage=75"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256