# Fly.io app configuration for a long-polling Telegram bot
# Generated for RogueProject

app = "rogueproject-bot"
primary_region = "dfw"

[build]
  # Use Dockerfile in project root
  dockerfile = "Dockerfile"

# No exposed services — this app does not listen on HTTP ports.
# You can add services later if you introduce an HTTP endpoint.

[processes]
  app = "java -jar /app/app.jar"

[env]
  # Set these via `fly secrets set TELEGRAM_BOT_TOKEN=...`
  TELEGRAM_BOT_USERNAME = "CurrencyUzb_bot"

# If you want to pin VM resources, uncomment below
#[[vm]]
#  memory = "256mb"
#  cpu_kind = "shared"
#  cpus = 1
