# Fly.io app configuration for a long-polling Telegram bot (no HTTP service)
# Updated to run via Dockerfile and Machines platform without exposed ports.

app = 'rogue-currency-t95i4a'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

# No exposed services — this bot uses Telegram long polling and does not listen on a port.

[env]
  # Set TELEGRAM_BOT_TOKEN via Fly secrets:
  #   flyctl secrets set TELEGRAM_BOT_TOKEN=123:ABC
  TELEGRAM_BOT_USERNAME = "CurrencyUzb_bot"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
